# Generated by Django 4.1 on 2022-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='название проекта')),
                ('product_description', models.TextField(verbose_name='о чём проект?')),
                ('pub_field', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Каталог',
            },
        ),
    ]
