# Generated by Django 4.1 on 2022-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_pub_field_project_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_price',
            field=models.CharField(max_length=200, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/product/'),
        ),
    ]
