# Generated by Django 4.1 on 2022-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_product_price_alter_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_price', models.CharField(max_length=200, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main/static/img/product/')),
            ],
            options={
                'verbose_name': 'Масло',
                'verbose_name_plural': 'Масла',
            },
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_price', models.CharField(max_length=200, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main/static/img/product/')),
            ],
            options={
                'verbose_name': 'Запчасти',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Autochemistry',
        ),
        migrations.AlterModelOptions(
            name='autochemistry',
            options={'verbose_name': 'Автохимия', 'verbose_name_plural': 'Автохимия'},
        ),
    ]
