# Generated by Django 4.1 on 2022-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_users_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
